# Section 13: Data Analysis with Python

## 13.1 NumPy in Python
- NumPy is a fundamental library for scentific computing in Python. It provides support for arrays and matrices alog with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basic of NumPy, focusing on arrays and vectorized operations.
- Even in deep learnign modules we will be using NumPy some or the other way. With the help of NumPy librarirs we will be able to create arrays, we will be able to work with matrices and all the mathematical operations.

In [1]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
# Create arrays from numpy

arr1 = np.array([1,2,3,4,5,6,7,])
arr1
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(7,)


In [5]:
## Reshaping Array
arr2 = np.array([5,6,7,8,9,10,11,12])
print(arr2.reshape(1,8))
print(arr2.reshape(2,4))

[[ 5  6  7  8  9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
# 2D Array
arr3 = np.array([[4,5,6],[7,8,9],[11,34,35],[67,87,0]])
print(arr3)
print(type(arr3))
print(arr3.shape)

[[ 4  5  6]
 [ 7  8  9]
 [11 34 35]
 [67 87  0]]
<class 'numpy.ndarray'>
(4, 3)


In [7]:
# arrange function
# Syntax: np.arrange(start, stop, step)

np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [8]:
np.arange(12, 44, 4).reshape(4,2)

array([[12, 16],
       [20, 24],
       [28, 32],
       [36, 40]])

### In-built Functions present in NumPy

In [9]:
# In-built Functions present in NumPy

np.ones((3,4))
# it will create an 2D array of size (3,4) with all the elements as 1.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

print("array: \n", arr)
print("Shape: ", arr.shape)
print("Number of Dimensions: ", arr.ndim)
print("Size(No. of Elements): ", arr.size)
print("Data type: ", arr.dtype)
print("Item Size(in bytes): ", arr.itemsize)


array: 
 [[1 2 3 4]
 [5 6 7 8]]
Shape:  (2, 4)
Number of Dimensions:  2
Size(No. of Elements):  8
Data type:  int32
Item Size(in bytes):  4


In [12]:
# NumPy Vectorized Operations.
aarr1 = np.array([1,2,3,4,5,6])
aarr2 = np.array([34,56,76,42,13,45])

# Element wise Addition
print("Addition: ", aarr1+aarr2)

# Element wise Substraction
print("Substraction: ", aarr1-aarr2)

# Element wise Multiplication
print("Multiplication: ", aarr1*aarr2)

# Element wise Division
print("Division: ", aarr1/aarr2)

Addition:  [35 58 79 46 18 51]
Substraction:  [-33 -54 -73 -38  -8 -39]
Multiplication:  [ 34 112 228 168  65 270]
Division:  [0.02941176 0.03571429 0.03947368 0.0952381  0.38461538 0.13333333]


In [13]:
## Universal Functions

arr = np.array([4,5,6,7,8,13,99,44])

# Square root
print("Square Root:",np.sqrt(arr))

# Exponential
print("Exponentail: ", np.exp(arr))

# Sine
print("Sine: ", np.sin(arr))

# Natural Log
print("Natural Log: ", np.log(arr))

Square Root: [2.         2.23606798 2.44948974 2.64575131 2.82842712 3.60555128
 9.94987437 6.63324958]
Exponentail:  [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 4.42413392e+05 9.88903032e+42 1.28516001e+19]
Sine:  [-0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825  0.42016704
 -0.99920683  0.01770193]
Natural Log:  [1.38629436 1.60943791 1.79175947 1.94591015 2.07944154 2.56494936
 4.59511985 3.78418963]


In [14]:
# Slicing and Indexing in array

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr1 = np.array([[2,3,45,5], [6,7,83,2], [45,67,89,34], [45,67,12,22], [90,54,67,25]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
arr[0][0]

1

In [16]:
arr1

array([[ 2,  3, 45,  5],
       [ 6,  7, 83,  2],
       [45, 67, 89, 34],
       [45, 67, 12, 22],
       [90, 54, 67, 25]])

In [17]:
# How to print rows....(from a starting)

arr1[1:] # From 1th col. to the last col.


array([[ 6,  7, 83,  2],
       [45, 67, 89, 34],
       [45, 67, 12, 22],
       [90, 54, 67, 25]])

In [18]:
# we can also do this...
arr1[2:, 2:]
# This will give you from 2nd row and 2nd col. (till the end)

array([[89, 34],
       [12, 22],
       [67, 25]])

In [19]:
# If we want to pickup 83, 2, 89, 34
arr1[1:3, 2:]
# When we write "1:3" as my 1st argument, it means we select row no. 1 till 2 (3 is exclusive), and for column we write "2:" 


array([[83,  2],
       [89, 34]])

In [20]:
# Modifying array elements
arr1[0,0] = 200
print(arr1)

[[200   3  45   5]
 [  6   7  83   2]
 [ 45  67  89  34]
 [ 45  67  12  22]
 [ 90  54  67  25]]


In [21]:
arr1[3:]=300
print(arr1)

[[200   3  45   5]
 [  6   7  83   2]
 [ 45  67  89  34]
 [300 300 300 300]
 [300 300 300 300]]


In [22]:
### Statistical Concept --> Normalization
# TO have a mean of 0 and Standard Deviation of 1

data = np.array([1,2,3,4,5])

# Calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalixed_data = (data - mean) / std_dev
print("Normalized Data: ", normalixed_data)

Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [23]:
### Statistical Concept --> Mean, Median, Mode, Variance, Standard Deviation

data1 = np.array([1,2,3,4,5,5,5,5,67,8,25,9,8,9,5,3,2,6,8,4,87,564,345,89,90,100])

# Mean
mean = np.mean(data1)
print("Mean: ", mean)

# Median
med = np.median(data1)
print("Median: ", med)

# Standard Deviation
std_dev = np.std(data1)
print("Standard Deviation: ", std_dev)

# Variance
variance = np.var(data1)
print("Variance: ", variance)

Mean:  56.11538461538461
Median:  7.0
Standard Deviation:  123.18320531227427
Variance:  15174.102071005917


In [24]:
# Logical Operation
 
data = np.array([134,2,34,4,5,6,0,3,7,89,22])

data [data > 5]

array([134,  34,   6,   7,  89,  22])

In [25]:
data[(data >= 5) & (data <= 40)]

array([34,  5,  6,  7, 22])

## 13.2 Pandas-DataFrames and Series.
- Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrames. 
- A Series is a one-dimensional array-like objects, while a DataFrame is a two-dimensional, size-mutable, and potentailly heterogeneous tabular data structure with labled axes (rows and columns). 

In [26]:
import pandas as pd

### --> Series
Series is a one-dimensional array-like objects that can hold any data type. It is similar to a column in a table.

In [27]:
# Series
data = [1,2,3,4,5,6,7,8,9,10]
series = pd.Series(data)
print("Series: \n", series)

Series: 
 0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64


In [28]:
# Creating Series from dictionary
data = {'a':1, 'b':2, 'c':3, 'd':4}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
d    4
dtype: int64


In [29]:
data=[345,678,987,654]
indexxx=['a','b','c','d']
pd.Series(data, index=indexxx)

a    345
b    678
c    987
d    654
dtype: int64

### DataFrames
DataFrames ar etwo dimensional mutable and heterogeneous tabular data structure with label axis that is rows and columns, its is similar to a table in a database or in an excel sheet.

In [54]:
# Creating DataFrame from a dictinory

data = {
    'Name': ['Om', 'Srishti', 'Himank', 'Vishwa'],
    'Age': [20, 21, 19, 22],
    'City': ['Mumbai', 'New York', 'Texas', 'Pune']
}

df = pd.DataFrame(data)
df


,Name,Age,City
0,Om,20,Mumbai
1,Srishti,21,New York
2,Himank,19,Texas
3,Vishwa,22,Pune


In [32]:
# Creating DataFraes from a list of Dictionaries

data = [
    {'Name':'Om', 'Age':24, 'State':'Himachal'},
    {'Name':'Himank', 'Age':94, 'State':'Rajasthan'},
    {'Name':'Srishti', 'Age':20, 'State':'Uttar Pradesh'},
    {'Name':'Devyani', 'Age':30, 'State':'Delhi'},
    {'Name':'Dev', 'Age':9, 'State':'Maharashtra'},
    {'Name':'Sid', 'Age':15, 'State':'Karnataka'}
]

df = pd.DataFrame(data)
print(df)


      Name  Age          State
0       Om   24       Himachal
1   Himank   94      Rajasthan
2  Srishti   20  Uttar Pradesh
3  Devyani   30          Delhi
4      Dev    9    Maharashtra
5      Sid   15      Karnataka


In [77]:
df = pd.read_csv('Amazon_Sale_Report.csv')
df

C:\Users\OM MAKWANA\AppData\Local\Temp\ipykernel_34204\1222257656.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Amazon_Sale_Report.csv')


,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False


In [38]:
df.shape

(128975, 24)

In [39]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN


In [40]:
df.tail()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,517.0,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.0,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,690.0,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.0,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,INR,696.0,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False


In [41]:
df['Order ID']

0         405-8078784-5731545
1         171-9198151-1101146
2         404-0687676-7273146
3         403-9615377-8133951
4         407-1069790-7240320
                 ...         
128970    406-6001380-7673107
128971    402-9551604-7544318
128972    407-9547469-3152358
128973    402-6184140-0545956
128974    408-7436540-8728312
Name: Order ID, Length: 128975, dtype: object

In [44]:
df.loc[20]
# To find info of a perticular column

index                                                           20
Order ID                                       405-0607769-0716360
Date                                                      04-30-22
Status                                                     Shipped
Fulfilment                                                  Amazon
Sales Channel                                            Amazon.in
ship-service-level                                       Expedited
Style                                                      JNE3795
SKU                                                JNE3795-KR-XXXL
Category                                                     kurta
Size                                                           3XL
ASIN                                                    B09HMXJVFS
Courier Status                                             Shipped
Qty                                                              1
currency                                                      

In [49]:
print(df.loc[3][3])
print(df.loc[3][5])


Cancelled
Amazon.in


C:\Users\OM MAKWANA\AppData\Local\Temp\ipykernel_34204\190976272.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.loc[3][3])
C:\Users\OM MAKWANA\AppData\Local\Temp\ipykernel_34204\190976272.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.loc[3][5])


In [51]:
## Accessing a specified element
df.at[20, 'Status']

'Shipped'

In [53]:
df.iat[20,4]

'Amazon'

### Data Manipulation

In [67]:
## Adding a Cloumn in th e Data set.
df['Salary'] = [500000, 600000, 50, 5]
df

,Name,Age,City,Salary
0,Om,20,Mumbai,500000
1,Srishti,21,New York,600000
2,Himank,19,Texas,50
3,Vishwa,22,Pune,5


In [68]:
## Remove a column
df.drop('Salary', axis = 1)


,Name,Age,City
0,Om,20,Mumbai
1,Srishti,21,New York
2,Himank,19,Texas
3,Vishwa,22,Pune


- If we try to drop the salary column then we willl get an error.

- Because drop function has two arguments,i.e. drop('Column name', axis = 0/1)

- Here, by default the axis value is "0". 0 - Row inddex, 1 - Column index


In [69]:
df

,Name,Age,City,Salary
0,Om,20,Mumbai,500000
1,Srishti,21,New York,600000
2,Himank,19,Texas,50
3,Vishwa,22,Pune,5


- Here, these drop changes are not permanent....
- To make it permanent we use 'inplace=True' argument. 

In [70]:
df.drop('Salary', axis = 1, inplace = True)


In [71]:
# Now the Salary column in deleted permanently.
df

,Name,Age,City
0,Om,20,Mumbai
1,Srishti,21,New York
2,Himank,19,Texas
3,Vishwa,22,Pune


In [72]:
# We can also edit the whole column.
df['Age'] = df['Age']+1  

In [73]:
df

,Name,Age,City
0,Om,21,Mumbai
1,Srishti,22,New York
2,Himank,20,Texas
3,Vishwa,23,Pune


In [74]:
# We can drop based on row
df.drop(3)

,Name,Age,City
0,Om,21,Mumbai
1,Srishti,22,New York
2,Himank,20,Texas


In [75]:
# Well, this is not permanent, to make it permanent we use implace attribute.
df.drop(3, inplace = True)

In [76]:
df

,Name,Age,City
0,Om,21,Mumbai
1,Srishti,22,New York
2,Himank,20,Texas


In [78]:
df.describe()

,index,Qty,Amount,ship-postal-code
count,128975.000000,128975.000000,121180.000000,128942.000000
mean,64487.000000,0.904431,648.561465,463966.236509
std,37232.019822,0.313354,281.211687,191476.764941
min,0.000000,0.000000,0.000000,110001.000000
25%,32243.500000,1.000000,449.000000,382421.000000
50%,64487.000000,1.000000,605.000000,500033.000000
75%,96730.500000,1.000000,788.000000,600024.000000
max,128974.000000,15.000000,5584.000000,989898.000000


## 13.3 Data Manipulation with Pandas and Numpy

In [1]:
import pandas as pd

In [12]:
df = pd.read_csv('Amazon_Sale_Report.csv')
df

C:\Users\OM MAKWANA\AppData\Local\Temp\ipykernel_24864\1222257656.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Amazon_Sale_Report.csv')


,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False


In [13]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN


In [14]:
df.describe()

,index,Qty,Amount,ship-postal-code
count,128975.000000,128975.000000,121180.000000,128942.000000
mean,64487.000000,0.904431,648.561465,463966.236509
std,37232.019822,0.313354,281.211687,191476.764941
min,0.000000,0.000000,0.000000,110001.000000
25%,32243.500000,1.000000,449.000000,382421.000000
50%,64487.000000,1.000000,605.000000,500033.000000
75%,96730.500000,1.000000,788.000000,600024.000000
max,128974.000000,15.000000,5584.000000,989898.000000


In [15]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [16]:
df.isnull().any(axis=0)

index                 False
Order ID              False
Date                  False
Status                False
Fulfilment            False
Sales Channel         False
ship-service-level    False
Style                 False
SKU                   False
Category              False
Size                  False
ASIN                  False
Courier Status         True
Qty                   False
currency               True
Amount                 True
ship-city              True
ship-state             True
ship-postal-code       True
ship-country           True
promotion-ids          True
B2B                   False
fulfilled-by           True
Unnamed: 22            True
dtype: bool

In [18]:
# Filling missing values with the mean of the column.
df['Amount_fillna'] = df['Amount'].fillna(df['Amount'].mean())
df

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22,Amount_fillna
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN,647.62
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN,406.00
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN,329.00
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN,753.33
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN,574.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,517.00,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False,517.00
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False,999.00
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,690.00,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False,690.00
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False,1199.00


In [19]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
Amount_fillna             0
dtype: int64

In [20]:
df.dtypes

index                   int64
Order ID               object
Date                   object
Status                 object
Fulfilment             object
Sales Channel          object
ship-service-level     object
Style                  object
SKU                    object
Category               object
Size                   object
ASIN                   object
Courier Status         object
Qty                     int64
currency               object
Amount                float64
ship-city              object
ship-state             object
ship-postal-code      float64
ship-country           object
promotion-ids          object
B2B                      bool
fulfilled-by           object
Unnamed: 22            object
Amount_fillna         float64
dtype: object

In [21]:
# Renaming column
df = df.rename(columns={'Date':'Sales Date'})

In [22]:
df.dtypes

index                   int64
Order ID               object
Sales Date             object
Status                 object
Fulfilment             object
Sales Channel          object
ship-service-level     object
Style                  object
SKU                    object
Category               object
Size                   object
ASIN                   object
Courier Status         object
Qty                     int64
currency               object
Amount                float64
ship-city              object
ship-state             object
ship-postal-code      float64
ship-country           object
promotion-ids          object
B2B                      bool
fulfilled-by           object
Unnamed: 22            object
Amount_fillna         float64
dtype: object

In [25]:
# Change Data Types
df['Amount_new'] = df['Amount_fillna'].astype(int)
# This does not work if the column has a missing values...
df.dtypes



index                   int64
Order ID               object
Sales Date             object
Status                 object
Fulfilment             object
Sales Channel          object
ship-service-level     object
Style                  object
SKU                    object
Category               object
Size                   object
ASIN                   object
Courier Status         object
Qty                     int64
currency               object
Amount                float64
ship-city              object
ship-state             object
ship-postal-code      float64
ship-country           object
promotion-ids          object
B2B                      bool
fulfilled-by           object
Unnamed: 22            object
Amount_fillna         float64
Amount_new              int32
dtype: object

In [26]:
df['New_Amount'] = df['Amount'].apply(lambda x:x*2)

df

,index,Order ID,Sales Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22,Amount_fillna,Amount_new,New_Amount
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN,647.62,647,1295.24
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN,406.00,406,812.00
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN,329.00,329,658.00
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN,753.33,753,1506.66
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN,574.00,574,1148.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,TELANGANA,500013.0,IN,NaN,False,NaN,False,517.00,517,1034.00
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False,999.00,999,1998.00
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,TELANGANA,500049.0,IN,NaN,False,NaN,False,690.00,690,1380.00
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False,1199.00,1199,2398.00


### --> Data Aggregating and Grouping

In [27]:
grouped_mean = df.groupby('Category')['Amount_fillna'].mean()
print(grouped_mean)

Category
Blouse           526.558797
Bottom           371.907294
Dupatta          305.000000
Ethnic Dress     719.605450
Saree            791.285446
Set              821.469261
Top              531.367435
Western Dress    756.924362
kurta            468.131622
Name: Amount_fillna, dtype: float64


In [30]:
# Groupby with 2 parameters(2 columns)
grouped_sum = df.groupby(['Category', 'ship-state'])['Amount_fillna'].sum()
print(grouped_sum)

Category  ship-state    
Blouse    ANDHRA PRADESH    1.763056e+04
          ASSAM             6.786000e+03
          BIHAR             8.928561e+03
          CHANDIGARH        3.770000e+02
          CHHATTISGARH      3.744801e+03
                                ...     
kurta     WEST BENGAL       1.245458e+06
          delhi             3.215000e+03
          goa               1.042000e+03
          punjab            2.861561e+03
          rajsthan          5.210000e+02
Name: Amount_fillna, Length: 323, dtype: float64


In [31]:
# Aggregate multiple functions.
aggre_grpby = df.groupby('ship-state')['Amount_fillna'].agg(['mean', 'sum', 'count'])
aggre_grpby

,mean,sum,count
ship-state,,,
ANDAMAN & NICOBAR,652.931831,1.678035e+05,257
ANDHRA PRADESH,637.761007,3.463042e+06,5430
APO,648.561465,6.485615e+02,1
AR,493.000000,4.930000e+02,1
ARUNACHAL PRADESH,707.623619,9.977493e+04,141
...,...,...,...
goa,493.400000,2.467000e+03,5
orissa,597.000000,5.970000e+02,1
punjab,662.182962,9.270561e+03,14


### --> Merging and Joining DataFrames

In [40]:
df1 = pd.DataFrame({'Key':['A','B','C'], 'Values1':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','D'], 'Values2':[4,5,6]})

In [41]:
df1

,Key,Values1
0,A,1
1,B,2
2,C,3


In [42]:
df2

,Key,Values2
0,A,4
1,B,5
2,D,6


In [43]:
# Merge the DataFrame on the 'Key' Column

pd.merge(df1, df2,on="Key", how = "inner")
# Inner joint means joint form left and right handside, basically both are considered.

,Key,Values1,Values2
0,A,1,4
1,B,2,5


In [44]:
pd.merge(df1, df2,on="Key", how = "outer")
# Here bothe the datasets are considered.

,Key,Values1,Values2
0,A,1.0,4.0
1,B,2.0,5.0
2,C,3.0,NaN
3,D,NaN,6.0


In [45]:
pd.merge(df1, df2,on="Key", how = "left")
# Here more priorities are given to the left dataframe....left outer joint

,Key,Values1,Values2
0,A,1,4.0
1,B,2,5.0
2,C,3,NaN


In [46]:
pd.merge(df1, df2,on="Key", how = "right")
# Here more priorities are given to the right dataset....Right outer joint

,Key,Values1,Values2
0,A,1.0,4
1,B,2.0,5
2,D,NaN,6


## 13.4 Reading Data from Different Sources.

In [48]:
import pandas as pd
from io import StringIO

In [52]:
Data = '{"employee_name":"James", "email":"james@gmail.com", "job_profile":[{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df  = pd.read_json(StringIO(Data))
df


,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."


In [53]:
# Now we will convert this back to json
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

- There's a difference between the above JSON file and the original json file. So in the above code we have not given any parameter, and that parameter is called "orient". By default orient is baesd on index value.
- Its taking the combination of index and the data value.(with column ns=ame in the front)

In [54]:
df.to_json(orient="index") # Index is the default parameter

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [55]:
df.to_json(orient="records")

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [58]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"

df = pd.read_csv(url, header=None)

In [59]:
df.to_csv("wine.csv")

In [62]:
url = "https://www.fdic.gov/bank-failures/failed-bank-list/"

df = pd.read_html(url)
df

[                               Bank Name               City          State  \
 0     The First National Bank of Lindsay            Lindsay       Oklahoma   
 1  Republic First Bank dba Republic Bank       Philadelphia   Pennsylvania   
 2                          Citizens Bank           Sac City           Iowa   
 3               Heartland Tri-State Bank            Elkhart         Kansas   
 4                    First Republic Bank      San Francisco     California   
 5                         Signature Bank           New York       New York   
 6                    Silicon Valley Bank        Santa Clara     California   
 7                      Almena State Bank             Almena         Kansas   
 8             First City Bank of Florida  Fort Walton Beach        Florida   
 9                   The First State Bank      Barboursville  West Virginia   
 
     Cert                 Aquiring Institution      Closing Date  \
 0   4134   First Bank & Trust Co., Duncan, OK  October 18, 2

In [63]:
df[0]

,Bank Name,City,State,Cert,Aquiring Institution,Closing Date,Fund Sort ascending
0,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,"First Bank & Trust Co., Duncan, OK","October 18, 2024",10547
1,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
2,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
3,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
4,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
5,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
6,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
7,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
8,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
9,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536


In [65]:
url = "https://en.wikipedia.org/wiki/Mobile_country_code"

df = pd.read_html(url, match="Country", header = 0) 
# Match is a parameter that takes keywords as input and according to that keyword it selects the data. 

In [66]:
df[0]

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN


### --> Pickle File
- Pickle in Python is primarily used in serializing and deserializing a Python object structure. In other words, it's the process of converting a Python object into a byte store it in a file/database, maintain program state across sessions, or transport data over the network.

In [69]:
df_excel = pd.read_excel('Book1.xlsx')
df_excel

,Name,Age
0,Om,20
1,Srishti,21
2,Bhoomi,17
3,Arhcee,22
4,Dhruv,20


In [70]:
df_excel.to_pickle('df_excel')

In [71]:
pd.read_pickle('df_excel')

,Name,Age
0,Om,20
1,Srishti,21
2,Bhoomi,17
3,Arhcee,22
4,Dhruv,20
